# Generated by Django 5.2 on 2025-04-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_seen_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='seen_guide',
            new_name='saw_guide',
        ),
    ]
