# Generated by Django 5.2 on 2025-04-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_seen_guide_customuser_saw_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='saw_guide',
        ),
    ]
