# Generated by Django 6.0.1 on 2026-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_email_otp_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
