# Generated by Django 5.2 on 2025-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Schedule assignments',
                'db_table': 'dm_schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeskData',
            fields=[
                ('desk_id', models.CharField(default='desk_', max_length=100, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=200)),
            ],
            options={
                'verbose_name_plural': 'Desks',
                'db_table': 'dm_desks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('room_id', models.CharField(default='none', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'dm_rooms',
                'managed': True,
            },
        ),
    ]
