# Generated by Django 5.2 on 2025-04-24 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookschedule',
            name='desk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookschedule',
            name='desk_id',
            field=models.ForeignKey(blank=True, db_column='desk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='desks.deskdata'),
        ),
        migrations.AddField(
            model_name='deskdata',
            name='room_id',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='desks.roomdata'),
        ),
        migrations.AddConstraint(
            model_name='bookschedule',
            constraint=models.UniqueConstraint(fields=('desk_user', 'claim_day'), name='unique_user_per_day'),
        ),
    ]
