# Generated by Django 5.2 on 2025-04-29 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookschedule',
            constraint=models.UniqueConstraint(fields=('desk_id', 'claim_day'), name='one_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='deskdata',
            constraint=models.UniqueConstraint(fields=('desk_id',), name='unique_desk_id'),
        ),
    ]
