# Generated by Django 6.0.1 on 2026-01-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0003_bookschedule_one_user_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorData',
            fields=[
                ('floor_id', models.CharField(default='floor_', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Floors',
                'db_table': 'dm_floors',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='bookschedule',
            name='claim_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')]),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='room_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='roomdata',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='desks.floordata'),
        ),
    ]
