# Generated by Django 6.0.1 on 2026-01-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0004_floordata_alter_bookschedule_claim_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='room_id',
            field=models.CharField(default='room_', max_length=50, primary_key=True, serialize=False),
        ),
    ]
