# Generated by Django 6.0.1 on 2026-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0005_roomdata_updated_at_alter_roomdata_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='floordata',
            name='floor_label',
            field=models.CharField(default='Piętro ', max_length=100),
        ),
    ]
