# Generated by Django 6.0.1 on 2026-02-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0006_floordata_floor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='room_label',
            field=models.CharField(default='Pokój ', max_length=50),
        ),
    ]
